name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.17.0"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: ðŸ“¦ Install dependencies
        run: yarn --frozen-lockfile

      - name: ðŸ”¨ Package
        run: yarn run package

      # Stable releases
      - name: Package and publish stable extension in the marketplace and OpenVSX
        if: "!github.event.release.prerelease"
        run: |
          yarn run package_release
          node_modules/.bin/vsce publish --packagePath ruby-environments.vsix
          node_modules/.bin/ovsx publish ruby-environments.vsix -p ${{ secrets.OPENVSX_TOKEN }} --yarn
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish types to npm
        if: "!github.event.release.prerelease"
        run: |
          cd npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Prereleases
      - name: Package and publish prerelease extension in the marketplace
        if: "github.event.release.prerelease"
        run: |
          yarn run package_prerelease
          node_modules/.bin/vsce publish --pre-release --packagePath ruby-environments.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish prerelease types to npm
        if: "github.event.release.prerelease"
        run: |
          cd npm
          npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
